Task/ds 14
diging/schedule-rest pull request #12
Opened 2021-04-29 18:58 UTC by sudheerad9

Added api's for create/update/delete user for admins, serializer for admin access.

2021-04-29 19:07 UTC, sudheerad9 commented on accounts/models.py
> -	@property
Was getting an error when trying to modify is_staff so removed it.
https://stackoverflow.com/questions/62504785/typeerror-user-got-an-unexpected-keyword-argument-is-staff-when-using-custo

2021-04-30 16:27 UTC, tjquinn1 requested changes

2021-04-30 16:27 UTC, tjquinn1 commented on accounts/serializers.py
> +		if not is_active:
Just set the default value when trying to get is_active. .get('is_active', False). Also is_active should be set to True by default so there should be no need to set it to true again.

2021-04-30 16:27 UTC, closed without merging

2021-04-30 16:40 UTC, sudheerad9 commented on accounts/models.py
> -	@property
If the @property method is removed , I was able to modify it.

2021-04-30 17:07 UTC, sudheerad9 commented on accounts/models.py
> -	@property
I was able to modify is_staff value after removing the @property method.